### ISSUE TITLE
Fails to read catalog.xml from THREDDS version 4.2.10

### ISSUE THREAD

**Issue by MBARIMike** [asascience-open/thredds_crawler#16]
In trying to crawl the catalog at http://dods.ndbc.noaa.gov/thredds/catalog/oceansites/DATA/MBARI/metadata/catalog.html I get this error:

```
  File "/home/vagrant/dev/stoqsgit/venv-stoqs/lib/python2.7/site-packages/thredds_crawler/crawl.py", line 131, in _run
    dt = datetime.strptime(date_tag.text, '%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=pytz.utc)
  File "/usr/local/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2011-01-04 14:43:14Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
```
This is using version 1.2.0 installed from PyPI.

**Comment by MBARIMike** [comment]
I just cloned this repo, pointed my crawler to the clone and thredds-crawler is working fine against TDS version 4.2.10. Perhaps a new version should be pushed to PyPI ?

**Comment by kwilcox** [comment]
@MBARIMike I can confirm that this is fixed. I'll get a new release out today.

**Comment by kwilcox** [comment]
@MBARIMike Can you test a newer version? This seems fixed.
