### ISSUE TITLE
Index Error when serviceType = "Resolver"

### ISSUE THREAD

**Issue by akauer** [asascience-open/thredds_crawler#8]
I tried using thredds_crawler on the test datasets that comes with THREDDS. There is an error (IndexError: string index out of range in File "/home/pydev/miniconda/envs/ncweb/lib/python2.7/site-packages/thredds_crawler/utils.py", line 8) for the enhancedCatalog. It appears to be an issue with the serviceType which is "Resolver" in this case.

**Comment by kwilcox** [comment]
:+1:
